In [30]:
import pandas as pd
import numpy as np

In [31]:
df = pd.read_csv("titanic_data.csv")

In [32]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

Checking NaN Values

In [33]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [34]:
df.tail(5)

PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00   NaN        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [35]:
df = df.drop('Cabin', axis=1)

In [36]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Embarked  
0      0         A/5 21171   7.2500        S  
1      0          PC 17599  71.2833        C  
2      0  STON/O2. 3101282   7.9250        S  
3      0            113803  53.1000        S  
4      0            373450   8.0500        S

There are some rows of Age which have none value. Let's fill it by taking the mean of the age.

In [37]:
df["Age"].mean()

29.69911764705882

In [38]:
mean_age = round(df["Age"].mean(), 2)
mean_age

29.7

In [39]:
df["Age"] = df["Age"].fillna(mean_age)

In [40]:
df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       2
dtype: int64

Dropping the two rows of Embarked column because it a categorical data so we can't take mean of it. 

In [41]:
df = df.dropna(subset=["Embarked"])

In [42]:
df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [43]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Embarked  
0      0         A/5 21171   7.2500        S  
1      0          PC 17599  71.2833        C  
2      0  STON/O2. 3101282   7.9250        S  
3      0            113803  53.1000        S  
4      0            373450   8.0500        S

Encoding of Categorical Data which will be our Feature Variable i.e Sex and Embarked.

1.) Using Map: We use map function for encoding the Sex column.

In [44]:
df['Sex'] = df['Sex'].map({"male":0, "female":1})

In [46]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    0  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1      0   
2                             Heikkinen, Miss. Laina    1  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1      0   
4                           Allen, Mr. William Henry    0  35.0      0      0   

             Ticket     Fare Embarked  
0         A/5 21171   7.2500        S  
1          PC 17599  71.2833        C  
2  STON/O2. 3101282   7.9250        S  
3            113803  53.1000        S  
4            373450   8.0500        S

2.) Using Label Encode: We use LabelEncoder for Embarked column.

In [47]:
from sklearn.preprocessing import LabelEncoder

In [48]:
df["Embarked"] = LabelEncoder().fit_transform(df["Embarked"])

In [49]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    0  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1      0   
2                             Heikkinen, Miss. Laina    1  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1      0   
4                           Allen, Mr. William Henry    0  35.0      0      0   

             Ticket     Fare  Embarked  
0         A/5 21171   7.2500         2  
1          PC 17599  71.2833         0  
2  STON/O2. 3101282   7.9250         2  
3            113803  53.1000         2  
4            373450   8.0500         2

Normalization

We will normalize the column Fare and Age in the range of 0 to 1.

Normalizing the Fare

In [50]:
from sklearn.preprocessing import MinMaxScaler

In [51]:
df["Fare"] = MinMaxScaler().fit_transform(df[["Fare"]])

In [112]:
df.head(2)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   

                                                Name  Sex       Age  SibSp  \
0                            Braund, Mr. Owen Harris    0  0.271174      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    1  0.472229      1   

   Parch     Ticket      Fare  Embarked  
0      0  A/5 21171  0.014151         2  
1      0   PC 17599  0.139136         0

Normalizing the Age

In [58]:
df["Age"] = MinMaxScaler().fit_transform(df[["Age"]])

In [59]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex       Age  SibSp  \
0                            Braund, Mr. Owen Harris    0  0.271174      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    1  0.472229      1   
2                             Heikkinen, Miss. Laina    1  0.321438      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  0.434531      1   
4                           Allen, Mr. William Henry    0  0.434531      0   

   Parch            Ticket      Fare  Embarked  
0      0         A/5 21171  0.014151         2  
1      0          PC 17599  0.139136         0  
2      0  STON/O2. 3101282  0.015469         2  
3      0            113803  0.103644         2  
4      0            373450  0.015713         2

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 889 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  889 non-null    int64  
 1   Survived     889 non-null    int64  
 2   Pclass       889 non-null    int64  
 3   Name         889 non-null    object 
 4   Sex          889 non-null    int64  
 5   Age          889 non-null    float64
 6   SibSp        889 non-null    int64  
 7   Parch        889 non-null    int64  
 8   Ticket       889 non-null    object 
 9   Fare         889 non-null    float64
 10  Embarked     889 non-null    int32  
dtypes: float64(2), int32(1), int64(6), object(2)
memory usage: 79.9+ KB


We will separate the Feature Varible and Target Variable

In [61]:
features = ["Pclass", "Sex", "Age", "SibSp", "Parch", "Fare", "Embarked"]
X = df[features].values
Y = df["Survived"].values

In [62]:
df[features]

Pclass  Sex       Age  SibSp  Parch      Fare  Embarked
0         3    0  0.271174      1      0  0.014151         2
1         1    1  0.472229      1      0  0.139136         0
2         3    1  0.321438      0      0  0.015469         2
3         1    1  0.434531      1      0  0.103644         2
4         3    0  0.434531      0      0  0.015713         2
..      ...  ...       ...    ...    ...       ...       ...
886       2    0  0.334004      0      0  0.025374         2
887       1    1  0.233476      0      0  0.058556         2
888       3    1  0.367932      1      2  0.045771         2
889       1    0  0.321438      0      0  0.058556         0
890       3    0  0.396833      0      0  0.015127         1

[889 rows x 7 columns]

In [64]:
# Get the features variable in numpy array
df[features].values

array([[3.        , 0.        , 0.27117366, ..., 0.        , 0.01415106,
        2.        ],
       [1.        , 1.        , 0.4722292 , ..., 0.        , 0.13913574,
        0.        ],
       [3.        , 1.        , 0.32143755, ..., 0.        , 0.01546857,
        2.        ],
       ...,
       [3.        , 1.        , 0.36793164, ..., 2.        , 0.04577135,
        2.        ],
       [1.        , 0.        , 0.32143755, ..., 0.        , 0.0585561 ,
        0.        ],
       [3.        , 0.        , 0.39683338, ..., 0.        , 0.01512699,
        1.        ]])

Train the model

In [65]:
from sklearn.model_selection import train_test_split

In [66]:
# Split the data in 70% and 30% for training and testing the model
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.03)

In [67]:
from sklearn.linear_model import LogisticRegression 

In [71]:
# Fit the Logistic Regression on the training dataset

model = LogisticRegression(max_iter=500)

In [72]:
model

LogisticRegression(max_iter=500)

In [73]:
# training
model.fit(X_train, Y_train) 

LogisticRegression(max_iter=500)

In [74]:
# Prediction 

Y_pred = model.predict(X_test)

In [75]:
# Check accuracy of model
from sklearn.metrics import accuracy_score

In [76]:
accuracy_model = accuracy_score(Y_test, Y_pred)*100

In [78]:
print('Logistic accuracy: ',accuracy_score(Y_test, Y_pred) *100 )

Logistic accuracy:  74.07407407407408


In [80]:
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.metrics import classification_report
#survived: 1
#not survived: 0

In [82]:
matrix = classification_report(Y_test, Y_pred,labels=[1,0])

print('Classification report : Logistic \n',matrix)

Classification report : Logistic 
               precision    recall  f1-score   support

           1       0.38      0.60      0.46         5
           0       0.89      0.77      0.83        22

    accuracy                           0.74        27
   macro avg       0.63      0.69      0.65        27
weighted avg       0.80      0.74      0.76        27



In [84]:
df['Survived'].value_counts()

0    549
1    340
Name: Survived, dtype: int64

In [85]:
340/ (549 + 340)

0.38245219347581555

In [86]:
accuracy_model

74.07407407407408

In [87]:
df.Survived.value_counts()

0    549
1    340
Name: Survived, dtype: int64

Evaluate the model

In [88]:
matrix = confusion_matrix(Y_test,Y_pred, labels=[1,0])
print('Confusion matrix : \n',matrix)

Confusion matrix : 
 [[ 3  2]
 [ 5 17]]


In [99]:
model


LogisticRegression(max_iter=500)

In [92]:
pwd

'C:\\Users\\Lenovo\\OneDrive\\Desktop\\Juypter_projects'

In [93]:
import joblib

In [95]:
# Save the model as pickel file
joblib.dump(model, "titanic_model.pkl")

['titanic_model.pkl']

In [96]:
# load the model from the file
loaded_model = joblib.load("titanic_model.pkl")

In [107]:
matrix = classification_report(Y_test,Y_pred,labels=[1,0])
print('Classification report : \n',matrix)

Classification report : 
               precision    recall  f1-score   support

           1       0.38      0.60      0.46         5
           0       0.89      0.77      0.83        22

    accuracy                           0.74        27
   macro avg       0.63      0.69      0.65        27
weighted avg       0.80      0.74      0.76        27



In [108]:
X_train[0]

array([1.        , 1.        , 0.25860769, 2.        , 2.        ,
       0.51212189, 0.        ])